title = "galotfa runtime parameters"
[global]
enable = true
outdir = "./otfLogs"      # path of the log directorys
filename = "galotfa.hdf5" # filename of the log file
maxiter = 25              # default 25
epsilon = 1e-10           # default 1e-8
[orbit]
enable = true
period = 10
method = "random"
idfile = "../validation/idlist.txt"
fraction = 0.9
logtypes = [2]
recenter.enable = true
recenter.method = "mbp"
recenter.radius = 10
recenter.iguess = [0, 0, 0]
recenter.anchorids = [2]
